name: Terraform plan
on:
  workflow_dispatch:

# Refer this Document for more info on permissions key
# http://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions
permissions: 
  id-token: write
  contents: read

jobs:
  terraform-plan:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: / #path from which all the script of your steps inside your job should run
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2
      
    - name: Azure Login
      uses: Azure/login@v3
      with:
        client-id: #client_id
        tenant-id: #tenant_id
        subscription-id: #subscription_id
        
    - name: Terraform init
      run: terraform init
      
    - name: Terraform fmt
      run: terraform fmt
      
    - name: Terraform validate
      run: terraform validate
      
    - name: Terraform plan
      run: terraform plan
   
      
  
  
