name: Practice_actions
on: 
  push:
    branches: 
      - 'features/PMR101'
      # - '!main'
  workflow_dispatch: 
permissions:
  id-token: write
  contents: read
env:
  ARM_SUBSCRIPTION_ID: 09d55635-2a09-4af6-9e93-6bb44383a7aa
jobs:
  terraform-plan:
    # environment: terraform-plan-run
    runs-on: self-hosted
    defaults: 
      run:
        working-directory: module/root_module
    steps: 
      - name: Checkout
        uses: actions/checkout@v6.0.3

      - name: Azure Login
        uses: Azure/login@v3
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Terraform init
        run: terraform init
        
      - name: Terraform fmt
        run: terraform fmt
        
      - name: Terraform validate
        run: terraform validate
        
      - name: Terraform plan
        run: terraform plan
  terraform-apply:
    needs: terraform-plan
    environment: terraform-apply-run
    runs-on: self-hosted
    defaults: 
      run:
        working-directory: module/root_module
    steps: 
      - name: Checkout
        uses: actions/checkout@v6.0.3

      - name: Azure Login
        uses: Azure/login@v3
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Terraform init
        run: terraform init
        
      - name: Terraform apply
        run: terraform apply -auto-approve



  
  

  
  
